import os
import sys
from flask import Blueprint, request, jsonify
from agent.stock_agent import StockAgent

# Create a Blueprint for the stock routes
stock_bp = Blueprint('stock_bp', __name__)

@stock_bp.route('/api/analyze', methods=['POST'])
def analyze_stock():
    """
    API Endpoint to analyze a stock based on user query.
    Expected JSON input: { "query": "Forecast Reliance for next year" }
    """
    try:
        # 1. Get data from the request
        data = request.get_json()
        
        if not data or 'query' not in data:
            return jsonify({
                "success": False, 
                "error": "Missing 'query' in request body"
            }), 400

        user_query = data['query']
        print(f"Received Query: {user_query}")  # Debug log

        # 2. Initialize the Stock Agent
        agent = StockAgent()

        # 3. Run the Agent (Pipeline Mode)
        # This now runs Historical -> Holdout -> Hyperopt in sequence
        response_text = agent.process_user_input(user_query)

        # 4. Retrieve the Dictionary of Images
        # The updated agent stores images in state["images"]
        images = agent.state.get("images", {})

        if not images:
            print("Warning: No images were generated by the pipeline.")

        # 5. Return JSON response to Frontend
        # We explicitly map the keys to ensure the frontend receives the expected structure
        return jsonify({
            "success": True,
            "analysis": response_text,  # The text explanation from Gemini
            "images": {
                "price_history": images.get("price_history"),
                "daily_returns": images.get("daily_returns"),
                "holdout_pred": images.get("holdout_pred"),
                "future_forecast": images.get("future_forecast")
            }
        })

    except Exception as e:
        print(f"Error processing stock analysis: {str(e)}")
        return jsonify({
            "success": False, 
            "error": "Internal Server Error", 
            "details": str(e)
        }), 500

# Simple health check route
@stock_bp.route('/api/health', methods=['GET'])
def health_check():
    return jsonify({"status": "Stock Analysis Service is running", "mode": "Indian Markets"})