import os
import sys
from flask import Blueprint, request, jsonify
from agent.stock_agent import StockAgent

# Create a Blueprint for the stock routes
stock_bp = Blueprint('stock_bp', __name__)

@stock_bp.route('/api/analyze', methods=['POST'])
def analyze_stock():
    """
    API Endpoint to analyze a stock based on user query.
    Expected JSON input: { "query": "Forecast Reliance for next year" }
    """
    try:
        # 1. Get data from the request
        data = request.get_json()
        
        if not data or 'query' not in data:
            return jsonify({
                "success": False, 
                "error": "Missing 'query' in request body"
            }), 400

        user_query = data['query']
        print(f"Received Query: {user_query}")  # Debug log

        # 2. Initialize the Stock Agent
        # The agent is responsible for parsing the query (e.g., extracting "RELIANCE.NS")
        # and deciding which model to run (Historical, Holdout, or Hyperopt).
        agent = StockAgent()

        # 3. Run the Agent
        # This triggers the LangGraph workflow:
        # Input -> Extract Info -> Route -> Model Execution -> Image Generation -> Response
        response_text = agent.process_user_input(user_query)

        # 4. Retrieve the Generated Image
        # The updated stock_agent.py saves the base64 image string into its state["image_data"]
        image_data = agent.state.get("image_data")

        if not image_data:
            print("Warning: No image was generated by the models.")

        # 5. Return JSON response to Frontend
        return jsonify({
            "success": True,
            "analysis": response_text,  # The text explanation from Gemini
            "image": image_data         # The Base64 encoded chart (or None if failed)
        })

    except Exception as e:
        print(f"Error processing stock analysis: {str(e)}")
        return jsonify({
            "success": False, 
            "error": "Internal Server Error", 
            "details": str(e)
        }), 500

# Simple health check route
@stock_bp.route('/api/health', methods=['GET'])
def health_check():
    return jsonify({"status": "Stock Analysis Service is running", "mode": "Indian Markets"})